/* eslint-disable react-refresh/only-export-components -- barrel de re-exports, no define componentes */
// FISCALO — Primitivas UI compartidas (barrel).
// Un archivo por componente; importa siempre desde '@/components/ui'.
export * from './Icon'
export * from './Btn'
export * from './Money'
export * from './Badge'
export * from './Avatar'
export * from './Image'
export * from './Card'
export * from './KPI'
export * from './Switch'
export * from './Tabs'
export * from './Pagination'
export * from './Modal'
export * from './Drawer'
export * from './Dropdown'
export * from './states'
export * from './charts'
export * from './PageHead'
